version: '3.0'

services:
  frontend:
    build: ./frontend
    restart: unless-stopped

  backend:
    build: ./backend
    env_file: .env
    environment:
      - KEY=${KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped