version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      NODE_OPTIONS: "--max-old-space-size=512"  # Limit memory usage for Node.js
    deploy:
      resources:
        limits:
          cpus: "2.0"  # Allow up to 2 CPU cores
          memory: "750M"  # Limit to 750MB to avoid RAM exhaustion

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    environment:
      UVICORN_WORKERS: "3"  # Use up to 3 workers for better performance
    deploy:
      resources:
        limits:
          cpus: "2.0"  # Allow up to 2 CPU cores
          memory: "1G"  # Allow up to 1GB RAM
