version: '3.0'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped